# Generated by Django 3.2.5 on 2021-09-09 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('Email', models.EmailField(max_length=256, verbose_name='Email Address')),
                ('Queries', models.TextField(verbose_name='Questions/Messages')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
