# Generated by Django 3.2.5 on 2021-09-09 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hire_end_date_time', models.DateTimeField()),
            ],
        ),
    ]
